author: B4F
author_url: https://www.brand4fans.com/
github_url: https://github.com/Brand4Fans/B4FSDK-iOS/
root_url: https://brand4fans.github.io/B4FSDK-iOS/
module: B4FSDK
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'B4FSDK.xcworkspace', -scheme, 'B4FSDK']
